# Datos de conexión
spring.datasource.url=jdbc:mysql://localhost:3306/motomanager_db?serverTimezone=UTC
spring.datasource.username=root
//spring.datasource.password=

# Estrategia de creación de tablas (Hibernate)
# 'update' creará las tablas automáticamente basado en tus clases Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
